version: '3.9'

services:
  nuxt-app:
    image: gelbooru-nuxt
    restart: unless-stopped
    build:
      context: './'
      dockerfile: 'Dockerfile'
    environment:
      PRODUCTION: 'true'
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nuxt-app:80/api/health"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 30s
