version: '3.9'

services:
  nuxt-app:
    image: gelbooru-nuxt
    restart: unless-stopped
    build:
      context: './'
      dockerfile: 'Dockerfile'
    environment:
      PRODUCTION: 'true'
    ports:
      - 80:80
